# Generated by Django 5.2.17 on 2026-08-27 00:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('capacity_mw', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('sido', models.CharField(blank=True, default='', help_text='지자체(시·군) — 계통/조례 조회 키', max_length=30)),
                ('facility_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('done', '완료'), ('active', '진행중'), ('wait', '대기'), ('risk', '리스크'), ('idle', '미착수')], default='active', max_length=10)),
                ('risk_tag', models.CharField(blank=True, default='', max_length=50)),
                ('risk_level', models.CharField(blank=True, choices=[('hi', '높음'), ('md', '중간')], default='', max_length=2)),
                ('pm_name', models.CharField(blank=True, default='', help_text='표시용 비정규화 — pm 미연결 시드 대비', max_length=50)),
                ('target_ntp', models.CharField(blank=True, default='', max_length=20)),
                ('approved_budget_krw', models.BigIntegerField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('energy_type', models.CharField(choices=[('solar', '태양광'), ('wind', '풍력')], default='solar', max_length=10)),
                ('lifecycle', models.CharField(choices=[('dev', '개발중'), ('ops', '운영중')], default='dev', max_length=5)),
                ('annual_gwh', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('cod', models.CharField(blank=True, default='', max_length=20)),
                ('address_detail', models.TextField(blank=True, default='', help_text='백데이터 — 목록 응답에는 내보내지 않는다')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pm', models.ForeignKey(blank=True, db_column='pm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bizdev_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사업지',
                'verbose_name_plural': '사업지',
                'db_table': 'bizdev_sites',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_no', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(blank=True, default='', max_length=100)),
                ('tier', models.CharField(choices=[('major', '상위'), ('minor', '하위')], default='minor', max_length=5)),
                ('status', models.CharField(choices=[('done', '완료'), ('active', '진행중'), ('wait', '대기'), ('risk', '리스크'), ('idle', '미착수')], default='idle', max_length=10)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('received_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('dday_label', models.CharField(blank=True, default='', help_text='deadline 없을 때 표시 문구(종결/예정/순번 등)', max_length=30)),
                ('doc_label', models.CharField(default='문서', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='bizdev.site')),
            ],
            options={
                'verbose_name': '인허가 단계',
                'verbose_name_plural': '인허가 단계',
                'db_table': 'bizdev_permit_stages',
                'ordering': ['stage_no'],
            },
        ),
        migrations.CreateModel(
            name='CommunityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', '진행중'), ('prog', '대응중'), ('closed', '완료')], default='open', max_length=10)),
                ('issue_type', models.CharField(choices=[('complaint', '민원성'), ('grid', '계통'), ('etc', '기타')], default='complaint', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bizdev.site')),
            ],
            options={
                'verbose_name': '지역수용성 이슈',
                'verbose_name_plural': '지역수용성 이슈',
                'db_table': 'bizdev_community_issues',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('land', '부지'), ('permit', '인허가'), ('design', '설계'), ('legal', '법무'), ('etc', '기타')], max_length=10)),
                ('amount_krw', models.BigIntegerField()),
                ('exec_date', models.DateField()),
                ('memo', models.TextField(blank=True, default='')),
                ('receipt_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('receipt_name', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bizdev_budget_entries', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='bizdev.site')),
            ],
            options={
                'verbose_name': '예산 집행',
                'verbose_name_plural': '예산 집행',
                'db_table': 'bizdev_budget_entries',
                'ordering': ['-exec_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('file_name', models.CharField(help_text='업로드 당시 원본 파일명', max_length=300)),
                ('storage_uri', models.CharField(help_text='/media/bizdev/permit_docs/<uuid>.<ext>', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bizdev_uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bizdev.permitstage')),
            ],
            options={
                'verbose_name': '인허가 문서',
                'verbose_name_plural': '인허가 문서',
                'db_table': 'bizdev_permit_documents',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'version'), name='uniq_bizdev_doc_version_per_stage'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('stage',), name='uniq_bizdev_current_doc_per_stage')],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['lifecycle'], name='bizdev_site_lifecyc_0c2f48_idx'),
        ),
        migrations.AddConstraint(
            model_name='permitstage',
            constraint=models.UniqueConstraint(fields=('site', 'stage_no'), name='uniq_bizdev_stage_no_per_site'),
        ),
        migrations.AddIndex(
            model_name='communityissue',
            index=models.Index(fields=['site', '-issue_date'], name='bizdev_comm_site_id_204d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['site', '-exec_date'], name='bizdev_budg_site_id_58a7ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_krw__gt', 0)), name='bizdev_budget_amount_positive'),
        ),
    ]
