# Generated by Django 5.2.15 on 2026-06-19 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel')], max_length=10)),
                ('storage_uri', models.CharField(help_text='원문 열람 경로', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='중복 적재 방지', max_length=128)),
                ('status', models.CharField(choices=[('uploaded', '업로드 완료'), ('parsing', '파싱 중'), ('embedding', '임베딩 중'), ('indexed', '인덱싱 완료'), ('failed', '실패')], default='uploaded', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='NULL이면 전사 공용 코퍼스', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workspaces.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='문서 내 순서')),
                ('content', models.TextField(help_text='청크 원문(스니펫/재정렬용)')),
                ('page_number', models.IntegerField(blank=True, help_text='출처 위치(페이지)', null=True)),
                ('section_title', models.CharField(blank=True, default='', help_text='조항/제목', max_length=300)),
                ('char_start', models.IntegerField(blank=True, null=True)),
                ('char_end', models.IntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, help_text='PDF 좌표(뷰어 하이라이트)', null=True)),
                ('sheet_name', models.CharField(blank=True, default='', help_text='Excel 시트명', max_length=200)),
                ('cell_range', models.CharField(blank=True, default='', help_text='Excel 셀 범위', max_length=100)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('qdrant_point_id', models.UUIDField(help_text='Qdrant 포인트 매핑', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': '문서 청크',
                'verbose_name_plural': '문서 청크',
                'db_table': 'document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
