# Generated by Django 5.2.16 on 2026-07-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_doc_type_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='유형별 맞춤 메타데이터'),
        ),
    ]
