# Generated by Django 5.2.16 on 2026-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('contract', '계약서'), ('report', '보고자료'), ('law', '법령/규정'), ('spec', '시방서/기술문서'), ('admin', '공문/행정문서'), ('general', '일반문서')], default='general', help_text='문서 분류 유형', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('pptx', 'PowerPoint')], max_length=10),
        ),
    ]
