# Generated by Django 5.2.16 on 2026-07-18 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_doc_type_alter_document_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text="표시 라벨 (예: '1.2')", max_length=20, unique=True)),
                ('major', models.PositiveIntegerField(help_text='메이저 번호 = 청킹 세대', unique=True)),
                ('collection_name', models.CharField(help_text='Qdrant 컬렉션명', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='청킹 방식 요약')),
                ('is_active', models.BooleanField(default=False, help_text='기본 질의 대상 버전')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'corpus_versions',
                'ordering': ['-major'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='corpus',
            field=models.ForeignKey(blank=True, help_text='소속 코퍼스 버전 (NULL=버전 도입 전 데이터)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.corpusversion'),
        ),
    ]
