# Generated by Django 5.2.16 on 2026-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word(97-2003)'), ('xlsx', 'Excel'), ('xlsm', 'Excel(매크로)'), ('pptx', 'PowerPoint')], max_length=10),
        ),
    ]
