# Generated by Django 5.2.16 on 2026-07-18 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='corpus_version',
            field=models.CharField(blank=True, default='', help_text='질의 대상 코퍼스 버전 (빈 값 = is_active 버전 사용)', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationshare',
            name='shared_by',
            field=models.ForeignKey(blank=True, db_column='shared_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
