# Generated by Django 5.2.16 on 2026-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_corpus_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='사이드바 상단 고정'),
        ),
    ]
