# Generated by Django 5.2.16 on 2026-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', '처리 중'), ('done', '완료'), ('partial', '중단됨'), ('failed', '실패')], default='done', max_length=12),
        ),
    ]
