# Generated by Django 5.2.16 on 2026-08-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='use_web_search',
            field=models.BooleanField(default=False, help_text='웹 검색 토글(대화별). 질문이 외부로 전송됨'),
        ),
        migrations.AddField(
            model_name='message',
            name='web_sources',
            field=models.JSONField(blank=True, help_text='웹 검색 근거 (표시용). 사내 출처는 MessageSource에 있다.', null=True),
        ),
    ]
