# Generated by Django 5.2.16 on 2026-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_use_web_search_message_web_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='llm_model',
            field=models.CharField(blank=True, default='', help_text='답변 생성 모델(대화별). 빈 값 = 서버 기본값', max_length=60),
        ),
    ]
