# Generated by Django 5.2.16 on 2026-07-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdraft',
            name='generated_articles',
            field=models.JSONField(blank=True, default=list, help_text='생성된 조항들'),
        ),
        migrations.AddField(
            model_name='contractdraft',
            name='inputs',
            field=models.JSONField(blank=True, default=dict, help_text='사용자 동적 입력값'),
        ),
        migrations.AddField(
            model_name='contractdraft',
            name='type_id',
            field=models.CharField(blank=True, default='', help_text='계약 유형 ID (PPA 등)', max_length=100),
        ),
        migrations.AddField(
            model_name='contractdraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_contract_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractdraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='contracts.contracttemplate'),
        ),
    ]
